<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Date_no_sale extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Date_no_sale_model');
    } 

    /*
     * Listing of date_no_sale
     */
    function index()
    {
        $data['date_no_sale'] = $this->Date_no_sale_model->get_all_date_no_sale();

        $data['_view'] = 'date_no_sale/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new date_no_sale
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('date','Date','required|alpha_numeric');
		$this->form_validation->set_rules('id_ticket','Id Ticket','required|alpha_numeric');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'date' => $this->input->post('date'),
				'id_ticket' => $this->input->post('id_ticket'),
            );
            
            $date_no_sale_id = $this->Date_no_sale_model->add_date_no_sale($params);
            redirect('date_no_sale/index');
        }
        else
        {            
            $data['_view'] = 'date_no_sale/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a date_no_sale
     */
    function edit($id_date)
    {   
        // check if the date_no_sale exists before trying to edit it
        $data['date_no_sale'] = $this->Date_no_sale_model->get_date_no_sale($id_date);
        
        if(isset($data['date_no_sale']['id_date']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('date','Date','required|alpha_numeric');
			$this->form_validation->set_rules('id_ticket','Id Ticket','required|alpha_numeric');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'date' => $this->input->post('date'),
					'id_ticket' => $this->input->post('id_ticket'),
                );

                $this->Date_no_sale_model->update_date_no_sale($id_date,$params);            
                redirect('date_no_sale/index');
            }
            else
            {
                $data['_view'] = 'date_no_sale/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The date_no_sale you are trying to edit does not exist.');
    } 

    /*
     * Deleting date_no_sale
     */
    function remove($id_date)
    {
        $date_no_sale = $this->Date_no_sale_model->get_date_no_sale($id_date);

        // check if the date_no_sale exists before trying to delete it
        if(isset($date_no_sale['id_date']))
        {
            $this->Date_no_sale_model->delete_date_no_sale($id_date);
            redirect('date_no_sale/index');
        }
        else
            show_error('The date_no_sale you are trying to delete does not exist.');
    }
    
}
